### ISSUE TITLE
TailwindCSS v. 1.1.2 Support

### ISSUE THREAD

**Issue by Mello21century** [manjumjn/gulp-with-tailwindcss#4]
Can I upgrade to TailwindCSS version 1.1.2 or is there any known issues u face?

Thanks

**Comment by Mello21century** [comment]
Ok I run it on tailwindcss 1.1.*
`
"tailwindcss": "^1.1.2"
`
in composer.json

`
@tailwind base;
`
in tailwind.scss

`
mv tailwind.js tailwind.js.backup
npx tailwind init tailwind.js --full
`
in terminal

**Comment by akoepcke** [comment]
@manjumjn Do you accept a PR to upgrade this whole thing to the current tailwind version?

**Comment by manjumjn** [comment]
@akoepcke I will. I'm little busy with other things and couldn't upgrade
